export const mockQuests = [
  {
    id: 15,
    type: "join_community",
    title: "Join the Worldcoin Discord",
    organization: "World",
    organizationLogo: "/world-logo.jpg",
    poolPrize: 50,
    prizeCurrency: "WLD",
    maxParticipants: 200,
    currentParticipants: 120,
    description:
      "Join our official Discord server and introduce yourself in the #introductions channel.",
  },
  {
    id: 16,
    type: "tutorial_creation",
    title: "Create a World ID Integration Tutorial",
    organization: "World",
    organizationLogo: "/world-logo.jpg",
    poolPrize: 0.05,
    prizeCurrency: "ETH",
    maxParticipants: 10,
    currentParticipants: 1,
    description:
      "Develop a step-by-step tutorial (video or written) on how to integrate World ID into a simple web app.",
  },
  {
    id: 17,
    type: "governance_vote",
    title: "Participate in Worldcoin Governance",
    organization: "World",
    organizationLogo: "/world-logo.jpg",
    poolPrize: 120,
    prizeCurrency: "USDC",
    maxParticipants: 75,
    currentParticipants: 30,
    description:
      "Cast your vote on the latest Worldcoin governance proposal and share your reasoning in our forum.",
  },
  {
    id: 6,
    type: "quote_tweet",
    title: "Quote A Tweet",
    organization: "World",
    organizationLogo: "/world-logo.jpg",
    poolPrize: 100,
    prizeCurrency: "WLD",
    maxParticipants: 50,
    currentParticipants: 10,
    description: "Quote the tweet, prove it, and earn up to 2 WLD.",
  },
  {
    id: 1,
    type: "quote_tweet",
    title: "Amplify Our Latest Announcement",
    organization: "ChainLink Labs",
    organizationLogo: "/chainlink-logo.svg",
    poolPrize: 150,
    prizeCurrency: "WLD",
    maxParticipants: 100,
    currentParticipants: 45,
    description:
      "Quote our latest tweet about the new protocol upgrade, add your insights, and tag 3 friends. Prove it with a screenshot!",
  },
  {
    id: 2,
    type: "referral",
    title: "Invite New Users to Our Community",
    organization: "Solana Foundation",
    organizationLogo: "/solana-logo.svg",
    poolPrize: 300,
    prizeCurrency: "WLD",
    maxParticipants: 30,
    currentParticipants: 12,
    description:
      "Refer 5 new active members to our official Telegram group. Each successful referral earns you a ticket into the prize draw!",
  },
  {
    id: 3,
    type: "quiz",
    title: "Test Your Blockchain Knowledge",
    organization: "Ethereum Foundation",
    organizationLogo: "/ethereum-foundation-logo.svg",
    poolPrize: 0.3,
    prizeCurrency: "ETH",
    maxParticipants: 200,
    currentParticipants: 110,
    description:
      "Complete our 10-question quiz on blockchain fundamentals and our project's unique features. Score 80% or higher to qualify!",
  },
  {
    id: 4,
    type: "video_creation",
    title: "Create a Short Explainer Video",
    organization: "Avalanche Network",
    organizationLogo: "/avalanche-logo.svg",
    poolPrize: 750,
    prizeCurrency: "USDC",
    maxParticipants: 15,
    currentParticipants: 3,
    description:
      "Produce a 1-3 minute video explaining a key feature of our platform or a recent development. Share it on YouTube/TikTok and tag us!",
  },
  {
    id: 5,
    type: "feedback_submission",
    title: "Give Feedback on Our Beta DApp",
    organization: "Oasis Network",
    organizationLogo: "/oasis-logo.svg",
    poolPrize: 0.4,
    prizeCurrency: "ETH",
    maxParticipants: 40,
    currentParticipants: 25,
    description:
      "Try out our beta DApp and provide detailed feedback on any bugs you find, suggestions for UX improvements, or ideas for new features using our dedicated feedback form.",
  },

  {
    id: 7,
    type: "swap_challenge",
    title: "Execute a Swap on 1inch",
    organization: "1inch Network",
    organizationLogo: "/1inch-logo.png",
    poolPrize: 120,
    prizeCurrency: "USDC",
    maxParticipants: 80,
    currentParticipants: 30,
    description:
      "Perform a token swap on the 1inch dApp, share your transaction hash, and explain your strategy.",
  },
  {
    id: 8,
    type: "research_summary",
    title: "Summarize Our Latest AI Research",
    organization: "ASI Alliance",
    organizationLogo: "/asi-alliance-logo.png",
    poolPrize: 0.2,
    prizeCurrency: "ETH",
    maxParticipants: 25,
    currentParticipants: 5,
    description:
      "Read our recent research paper on decentralized AI and write a concise summary (min. 300 words).",
  },
  {
    id: 9,
    type: "data_provider_challenge",
    title: "Explore Flare's Data Oracles",
    organization: "Flare Network",
    organizationLogo: "/flare-network-logo.png",
    poolPrize: 180,
    prizeCurrency: "WLD",
    maxParticipants: 60,
    currentParticipants: 20,
    description:
      "Interact with a data oracle on Flare, explain its utility, and share your findings on social media.",
  },
  {
    id: 10,
    type: "privacy_advocacy",
    title: "Champion Digital Privacy",
    organization: "Self Protocol",
    organizationLogo: "/self-protocol-logo.png",
    poolPrize: 220,
    prizeCurrency: "USDC",
    maxParticipants: 45,
    currentParticipants: 15,
    description:
      "Create a compelling social media post advocating for digital privacy using Self Protocol's features.",
  },
  {
    id: 11,
    type: "zk_explainer",
    title: "Demystify Zircuit's ZK-Rollup",
    organization: "Zircuit",
    organizationLogo: "/zircuit-logo.png",
    poolPrize: 0.1,
    prizeCurrency: "ETH",
    maxParticipants: 10,
    currentParticipants: 2,
    description:
      "Produce a simple, engaging explanation (video or article) of how Zircuit's ZK-rollup technology works.",
  },
  {
    id: 12,
    type: "wallet_onboarding",
    title: "Onboard a Friend to Walrus Wallet",
    organization: "Walrus Wallet",
    organizationLogo: "/walrus-logo.png",
    poolPrize: 100,
    prizeCurrency: "WLD",
    maxParticipants: 70,
    currentParticipants: 25,
    description:
      "Help a friend set up their first Walrus Wallet and make a test transaction. Provide proof of onboarding.",
  },
  {
    id: 13,
    type: "usdc_adoption",
    title: "Share Your USDC Use Case",
    organization: "Circle",
    organizationLogo: "/circle-logo.png",
    poolPrize: 90,
    prizeCurrency: "USDC",
    maxParticipants: 150,
    currentParticipants: 80,
    description:
      "Describe how you use USDC in your daily life or crypto activities in a short tweet or forum post.",
  },
  {
    id: 14,
    type: "nft_showcase",
    title: "Showcase Your Flow NFT",
    organization: "Flow Blockchain",
    organizationLogo: "/flow-logo.png",
    poolPrize: 170,
    prizeCurrency: "WLD",
    maxParticipants: 55,
    currentParticipants: 18,
    description:
      "Share your favorite NFT on the Flow blockchain, explain why you love it, and tag us!",
  },
];
